version: '3.3'
services:
    node_backend:
        container_name: node_backend
        image: 'nodejs'
        ports:
            - '8080:8080'
        depends_on:
            - db
        restart: always
    db:
        container_name: db
        image: 'postgres'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=postgres
        volumes:
            - /opt/data/volumes/pgdata:/var/lib/postgresql/data
            - /opt/data/quote_create_api/postgresinit.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    angular:
        container_name: angular_front
        image: 'angular'
        ports:
            - '80:80'
    
