version: '3.8'
services:
  node_backend:
    container_name: node_backend
    image: 'nodejs'
    ports:
      - '49160:8080'
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data